# festivals-database-node configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-address = "localhost"
port = 22397
key = "TEST_API_KEY_001"

[database]
bind-address = "localhost"
port = 3306

[heartbeat]
endpoint = "localhost"

[authentication]
admin-keys = ["TEST_API_KEY_001"]