# festivals-database-node configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-address = "localhost"
bind-host = "localhost"
port = 22397
key = "TEST_API_KEY_001"

[tls]
festivaslapp-root-ca = "/usr/local/festivals-database-node/ca.crt"
cert = "//usr/local/festivals-database-node/server.crt"
key = "/usr/local/festivals-database-node/ca.key"

[database]
bind-address = "localhost"
port = 3306

[heartbeat]
endpoint = "localhost"
interval = 6

[authentication]
admin-keys = ["TEST_API_KEY_001"]